version: 0.0
os: linux
files:
 - source: /exomind/
   destination: /home/ec2-user/exomind
 - source: /app/
   destination: /home/ec2-user/app
 - source: /utils/
   destination: /home/ec2-user/utils
 - source: /common/
   destination: /home/ec2-user/common
 - source: /crawler/
   destination: /home/ec2-user/crawler
 - source: /static/
   destination: /home/ec2-user/static
 - source: /test/
   destination: /home/ec2-user/test
 - source: /manage.py
   destination: /home/ec2-user
 - source: /supervisord.conf
   destination: /home/ec2-user
 - source: /requirements.txt
   destination: /home/ec2-user
 - source: /scripts/
   destination: /home/ec2-user/scripts

permissions:
  - object: /home/ec2-user/manage.py
    owner: ec2-user
    mode: 644
    type:
      - file
  - object: /home/ec2-user/supervisord.conf
    owner: ec2-user
    mode: 644
    type:
      - file
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 1200
      runas: root
    - location: scripts/codestar_remote_access
      timeout: 300
      runas: root
    - location: scripts/load_env
      timeout: 1200
      runas: root
    - location: scripts/migrate
      timeout: 1200
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root

  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
