version: 0.2

env:
  variables:
    # For running tests.
    SECRET_KEY: "YR!p41&onb1vgKDhvj6y@&B@hrw&2CXJ4BmF7k^Vi$k$mZjAek"

phases:
  install:
    commands:
      # Install dependencies needed for running tests
      - pip install --upgrade pip
      - pip install -r requirements.txt

  pre_build:
    commands:
      # Discover and run unit tests. For more information, see <https://docs.djangoproject.com/en/2.0/topics/testing/overview/>
      - python manage.py test

  post_build:
    commands:
      # Do not remove this statement. This command is required for AWS CodeStar projects.
      # Update the AWS Partition, AWS Region, account ID and project ID in the project ARN in template-configuration.json file so AWS CloudFormation can tag project resources.
      - sed -i.bak 's/\$PARTITION\$/'${PARTITION}'/g;s/\$AWS_REGION\$/'${AWS_REGION}'/g;s/\$ACCOUNT_ID\$/'${ACCOUNT_ID}'/g;s/\$PROJECT_ID\$/'${PROJECT_ID}'/g' template-configuration.json

artifacts:
  type: zip
  files:
    - 'template.yml'
    - 'exomind/**/*'
    - 'app/**/*'
    - 'common/**/*'
    - 'utils/**/*'
    - 'test/**/*'
    - 'static/**/*'
    - 'scripts/**/*'
    - 'crawler/**/*'
    - 'appspec.yml'
    - 'manage.py'
    - 'requirements.txt'
    - 'supervisord.conf'
    - 'template-configuration.json'
