# Generated by Django 2.2.5 on 2019-09-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewable',
            name='image_url',
            field=models.URLField(blank=True, max_length=32767, null=True),
        ),
    ]
