# Generated by Django 2.2.7 on 2019-11-29 00:17

from django.db import migrations, models
import django.db.models.deletion
import utils.b64id
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_reviewable_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=utils.fields.B64IDField(default=utils.b64id.b64id4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', utils.fields.B64IDField(default=utils.b64id.b64id4, editable=False)),
                ('type', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
        ),
    ]
