# Generated by Django 3.0.1 on 2019-12-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191129_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='reviewable',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=32767),
        ),
    ]
