# Generated by Django 3.0.2 on 2020-02-14 07:25

from django.db import migrations, models
import django.db.models.deletion
import utils.b64id
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191228_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', utils.fields.B64IDField(default=utils.b64id.b64id4, editable=False, primary_key=True, serialize=False)),
                ('entity_id', utils.fields.B64IDField(default=utils.b64id.b64id4, editable=False)),
                ('text', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('in_reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
        ),
    ]
