# Generated by Django 3.0.3 on 2020-02-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_comment'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['entity_id'], name='app_comment_entity__532831_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['in_reply_to'], name='app_comment_in_repl_af2831_idx'),
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['entity_id'], name='app_reactio_entity__27a89b_idx'),
        ),
    ]
