# Generated by Django 3.1.5 on 2021-01-24 22:28

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200216_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=django.contrib.postgres.fields.citext.CITextField(max_length=255, unique=True),
        ),
    ]
