#!/bin/bash
yum update
easy_install pip
pip install supervisor==4.1.0
yum -y install python37 python37-virtualenv
yum -y install python37-pip
python3.7 -m pip install virtualenv
cd /home/ec2-user
virtualenv .venv
source .venv/bin/activate
pip install -r requirements.txt
